version: 2.1
orbs:
  gradle: circleci/gradle@1.0.10
jobs:
  build-pony-inject:
    working_directory: ~/code
    docker:
      - image: circleci/openjdk:11-jdk
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout:
          path: ~/android/PonyInject
      - gradle/with_cache:
          steps:
            - run:
                name: Run Tests and Checks
                command: ./gradlew check
  build-pony-ktor:
    working_directory: ~/code
    docker:
      - image: circleci/openjdk:11-jdk
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout:
          path: ~/server/ponyktor
      - gradle/with_cache:
          steps:
            - run:
                name: Run Tests and Checks
                command: ./gradlew check
